//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionLinQMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleados()
        {
            this.tblJustificacionPersonal = new HashSet<tblJustificacionPersonal>();
            this.tblRegistroMarcas = new HashSet<tblRegistroMarcas>();
        }
    
        public int IdEmpleados { get; set; }
        public string Nombres { get; set; }
        public bool Activo { get; set; }
        public int IdDepartamento { get; set; }
        public int IdTurno { get; set; }
        public Nullable<double> Salario { get; set; }
        public string DiaLibre { get; set; }
    
        public virtual tblDepartamento tblDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJustificacionPersonal> tblJustificacionPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegistroMarcas> tblRegistroMarcas { get; set; }
        public virtual tblTurnos tblTurnos { get; set; }
    }
}
