//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionLinQMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistroMarcas
    {
        public int IdEmpleados { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> H_Ent1 { get; set; }
        public Nullable<System.DateTime> H_Sal1 { get; set; }
        public Nullable<System.DateTime> H_Ent2 { get; set; }
        public Nullable<System.DateTime> H_Sal2 { get; set; }
    
        public virtual tblEmpleados tblEmpleados { get; set; }
    }
}
