//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionLinQMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTurnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTurnos()
        {
            this.tblEmpleados = new HashSet<tblEmpleados>();
        }
    
        public int IdTurno { get; set; }
        public string Turno { get; set; }
        public System.DateTime Lunes_Sabado_Inicio { get; set; }
        public System.DateTime Lunes_Sabado_Fin { get; set; }
        public double HorasAlmuerzo { get; set; }
        public System.DateTime Almuerzo_Inicio { get; set; }
        public System.DateTime Almuerzo_Fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpleados> tblEmpleados { get; set; }
    }
}
